[global]
# Disable the deprecation warning for pyplot
showPyplotGlobalUse = false

[server]
# Configure server settings
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
# Configure browser settings
serverAddress = "localhost"
serverPort = 8501

[theme]
# Set the default theme
base = "dark"
primaryColor = "#1DB954"  # 선택사항: 강조 색상 설정
backgroundColor = "#000000"  # 검정 배경
secondaryBackgroundColor = "#1a1a1a"  # 카드 등 배경
textColor = "#FFFFFF"  # 흰색 텍스트
font = "sans serif"
