[global]
# Disable the deprecation warning for pyplot
showPyplotGlobalUse = false

[server]
# Configure server settings
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
# Configure browser settings
serverAddress = "localhost"
serverPort = 8501

[theme]
# Set the default theme
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
